# Generated by Django 4.2.6 on 2023-12-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_tag_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='anouncment',
            new_name='anouncement',
        ),
    ]
